# Generated by Django 3.2.8 on 2022-02-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baglocater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddLostAndFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('flightNumber', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=30)),
                ('baggageNumber', models.CharField(max_length=30)),
                ('departureAirport', models.CharField(max_length=30)),
                ('arrivalAirport', models.CharField(max_length=30)),
                ('departureDate', models.CharField(max_length=30)),
                ('arrivalDate', models.CharField(max_length=30)),
            ],
        ),
    ]
